version: '3.9'

services:
  pytorch_fastai:
    build: .
    ports:
      - "8888:8888"
      - "8866:8866"
    volumes:
      - D:/fastaidocker/notebooks:/workspace
    shm_size: '2g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - mynetwork

  # firefox:
  #   image: firefox
  #   ports:
  #     - "5900:5900"
  #     - "5999:5999"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
